services:
  postgres:
    image: postgres:16-alpine
    container_name: erp-db-users-postgres
    environment:
      POSTGRES_USER: adriano
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_users
    ports:
      - "5434:5432"
    volumes:
      - db_users_data:/var/lib/postgresql/data
    networks:
      - erp-db-users-network
    restart: unless-stopped
    command: ["postgres", "-c", "timezone=America/Lima"]

  app:
    image: eclipse-temurin:17-jre
    container_name: erp-ms-users
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    volumes:
      - ./target:/app
    working_dir: /app
    command: ["java", "-jar", "db_users-0.0.1-SNAPSHOT.jar"]
    networks:
      - erp-db-users-network
    restart: unless-stopped

volumes:
  db_users_data:

networks:
  erp-db-users-network:
    driver: bridge